//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPCRemote.UI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPCRemote.UI.Strings.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Constructor Reached..
        /// </summary>
        public static string App_Constructor_Reached {
            get {
                return ResourceManager.GetString("App_Constructor_Reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash in OnLaunched.
        /// </summary>
        public static string App_CriticalCrash {
            get {
                return ResourceManager.GetString("App_CriticalCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied font family: {Font}.
        /// </summary>
        public static string App_FontApplied {
            get {
                return ResourceManager.GetString("App_FontApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied font scale: {Scale}% ({Size}px).
        /// </summary>
        public static string App_FontScaleApplied {
            get {
                return ResourceManager.GetString("App_FontScaleApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied saved settings: Theme={Theme}, Font={Font}, Scale={Scale}%.
        /// </summary>
        public static string App_SettingsApplied {
            get {
                return ResourceManager.GetString("App_SettingsApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply saved settings.
        /// </summary>
        public static string App_SettingsApplyFailed {
            get {
                return ResourceManager.GetString("App_SettingsApplyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application shutting down....
        /// </summary>
        public static string App_ShuttingDown {
            get {
                return ResourceManager.GetString("App_ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occurred: {Message}.
        /// </summary>
        public static string App_UnhandledException {
            get {
                return ResourceManager.GetString("App_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launched app {Slot}: {Name} ({Path}).
        /// </summary>
        public static string AppCatalog_AppLaunched {
            get {
                return ResourceManager.GetString("AppCatalog_AppLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete app..
        /// </summary>
        public static string AppCatalog_DeleteFailed {
            get {
                return ResourceManager.GetString("AppCatalog_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch app {Slot}: {Name}.
        /// </summary>
        public static string AppCatalog_LaunchFailed {
            get {
                return ResourceManager.GetString("AppCatalog_LaunchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {Count} apps from service..
        /// </summary>
        public static string AppCatalog_Loaded {
            get {
                return ResourceManager.GetString("AppCatalog_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load app catalog..
        /// </summary>
        public static string AppCatalog_LoadFailed {
            get {
                return ResourceManager.GetString("AppCatalog_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reorder apps..
        /// </summary>
        public static string AppCatalog_ReorderFailed {
            get {
                return ResourceManager.GetString("AppCatalog_ReorderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save reordered app {Name}: {Error}.
        /// </summary>
        public static string AppCatalog_ReorderSaveFailed {
            get {
                return ResourceManager.GetString("AppCatalog_ReorderSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save app..
        /// </summary>
        public static string AppCatalog_SaveFailed {
            get {
                return ResourceManager.GetString("AppCatalog_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cancelled UAC prompt for {Slot}: {Name}.
        /// </summary>
        public static string AppCatalog_UacCancelled {
            get {
                return ResourceManager.GetString("AppCatalog_UacCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error loading app catalog..
        /// </summary>
        public static string AppCatalog_UnexpectedLoadError {
            get {
                return ResourceManager.GetString("AppCatalog_UnexpectedLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC connection error while fetching stats..
        /// </summary>
        public static string Dashboard_IpcError {
            get {
                return ResourceManager.GetString("Dashboard_IpcError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC error while fetching stats..
        /// </summary>
        public static string Dashboard_IpcException {
            get {
                return ResourceManager.GetString("Dashboard_IpcException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started stats polling with interval {Interval}s.
        /// </summary>
        public static string Dashboard_PollingStarted {
            get {
                return ResourceManager.GetString("Dashboard_PollingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped stats polling..
        /// </summary>
        public static string Dashboard_PollingStopped {
            get {
                return ResourceManager.GetString("Dashboard_PollingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error while fetching stats..
        /// </summary>
        public static string Dashboard_UnexpectedError {
            get {
                return ResourceManager.GetString("Dashboard_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service command &apos;{Command}&apos; executed successfully via UI..
        /// </summary>
        public static string Service_CommandExecuted {
            get {
                return ResourceManager.GetString("Service_CommandExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service command &apos;{Command}&apos; failed via UI..
        /// </summary>
        public static string Service_CommandFailed {
            get {
                return ResourceManager.GetString("Service_CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate service configuration file to update..
        /// </summary>
        public static string Service_ConfigNotFound {
            get {
                return ResourceManager.GetString("Service_ConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration saved successfully..
        /// </summary>
        public static string Service_ConfigSaved {
            get {
                return ResourceManager.GetString("Service_ConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save configuration..
        /// </summary>
        public static string Service_ConfigSaveFailed {
            get {
                return ResourceManager.GetString("Service_ConfigSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated service configuration at {Path}.
        /// </summary>
        public static string Service_ConfigUpdated {
            get {
                return ResourceManager.GetString("Service_ConfigUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write to service configuration file at {Path}.
        /// </summary>
        public static string Service_ConfigWriteFailed {
            get {
                return ResourceManager.GetString("Service_ConfigWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service installation failed: {Error}.
        /// </summary>
        public static string Service_InstallFailed {
            get {
                return ResourceManager.GetString("Service_InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing service from executable path {Path}.
        /// </summary>
        public static string Service_InstallStarted {
            get {
                return ResourceManager.GetString("Service_InstallStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service installed successfully via UI (sc create result cached)..
        /// </summary>
        public static string Service_InstallSuccess {
            get {
                return ResourceManager.GetString("Service_InstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restart service from the UI..
        /// </summary>
        public static string Service_RestartFailed {
            get {
                return ResourceManager.GetString("Service_RestartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service restarted successfully from the UI..
        /// </summary>
        public static string Service_RestartSuccess {
            get {
                return ResourceManager.GetString("Service_RestartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI triggered restart command for the Windows service..
        /// </summary>
        public static string Service_RestartTriggered {
            get {
                return ResourceManager.GetString("Service_RestartTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI triggered start command for the Windows service..
        /// </summary>
        public static string Service_StartTriggered {
            get {
                return ResourceManager.GetString("Service_StartTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to refresh service status..
        /// </summary>
        public static string Service_StatusRefreshFailed {
            get {
                return ResourceManager.GetString("Service_StatusRefreshFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI triggered stop command for the Windows service..
        /// </summary>
        public static string Service_StopTriggered {
            get {
                return ResourceManager.GetString("Service_StopTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service uninstallation failed: {Error}.
        /// </summary>
        public static string Service_UninstallFailed {
            get {
                return ResourceManager.GetString("Service_UninstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service uninstalled successfully via UI..
        /// </summary>
        public static string Service_UninstallSuccess {
            get {
                return ResourceManager.GetString("Service_UninstallSuccess", resourceCulture);
            }
        }
    }
}
