//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPCRemote.UI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPCRemote.UI.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is disabled..
        /// </summary>
        public static string AppCatalog_AppDisabled {
            get {
                return ResourceManager.GetString("AppCatalog_AppDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted &apos;{0}&apos; successfully..
        /// </summary>
        public static string AppCatalog_DeletedApp {
            get {
                return ResourceManager.GetString("AppCatalog_DeletedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete: {0}.
        /// </summary>
        public static string AppCatalog_DeleteFailed {
            get {
                return ResourceManager.GetString("AppCatalog_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting &apos;{0}&apos;....
        /// </summary>
        public static string AppCatalog_DeletingApp {
            get {
                return ResourceManager.GetString("AppCatalog_DeletingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch cancelled by user..
        /// </summary>
        public static string AppCatalog_LaunchCancelled {
            get {
                return ResourceManager.GetString("AppCatalog_LaunchCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launched &apos;{0}&apos;..
        /// </summary>
        public static string AppCatalog_LaunchedApp {
            get {
                return ResourceManager.GetString("AppCatalog_LaunchedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch: {0}.
        /// </summary>
        public static string AppCatalog_LaunchFailed {
            get {
                return ResourceManager.GetString("AppCatalog_LaunchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching &apos;{0}&apos;....
        /// </summary>
        public static string AppCatalog_LaunchingApp {
            get {
                return ResourceManager.GetString("AppCatalog_LaunchingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} apps..
        /// </summary>
        public static string AppCatalog_LoadedApps {
            get {
                return ResourceManager.GetString("AppCatalog_LoadedApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load apps: {0}.
        /// </summary>
        public static string AppCatalog_LoadFailed {
            get {
                return ResourceManager.GetString("AppCatalog_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading apps....
        /// </summary>
        public static string AppCatalog_LoadingApps {
            get {
                return ResourceManager.GetString("AppCatalog_LoadingApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has no path configured..
        /// </summary>
        public static string AppCatalog_NoPathConfigured {
            get {
                return ResourceManager.GetString("AppCatalog_NoPathConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path not found: {0}.
        /// </summary>
        public static string AppCatalog_PathNotFound {
            get {
                return ResourceManager.GetString("AppCatalog_PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps reordered successfully..
        /// </summary>
        public static string AppCatalog_ReorderedApps {
            get {
                return ResourceManager.GetString("AppCatalog_ReorderedApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reordering: {0}.
        /// </summary>
        public static string AppCatalog_ReorderFailed {
            get {
                return ResourceManager.GetString("AppCatalog_ReorderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reordering apps....
        /// </summary>
        public static string AppCatalog_ReorderingApps {
            get {
                return ResourceManager.GetString("AppCatalog_ReorderingApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot, Name, and Path are required..
        /// </summary>
        public static string AppCatalog_RequiredFields {
            get {
                return ResourceManager.GetString("AppCatalog_RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved &apos;{0}&apos; successfully..
        /// </summary>
        public static string AppCatalog_SavedApp {
            get {
                return ResourceManager.GetString("AppCatalog_SavedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save: {0}.
        /// </summary>
        public static string AppCatalog_SaveFailed {
            get {
                return ResourceManager.GetString("AppCatalog_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving app....
        /// </summary>
        public static string AppCatalog_SavingApp {
            get {
                return ResourceManager.GetString("AppCatalog_SavingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connor&apos;s PC Remote.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to service. Is it running?.
        /// </summary>
        public static string Dashboard_CannotConnect {
            get {
                return ResourceManager.GetString("Dashboard_CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to service....
        /// </summary>
        public static string Dashboard_ConnectingToService {
            get {
                return ResourceManager.GetString("Dashboard_ConnectingToService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated: {0}.
        /// </summary>
        public static string Dashboard_LastUpdated {
            get {
                return ResourceManager.GetString("Dashboard_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service error: {0}.
        /// </summary>
        public static string Dashboard_ServiceError {
            get {
                return ResourceManager.GetString("Dashboard_ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Catalog.
        /// </summary>
        public static string Nav_AppCatalog {
            get {
                return ResourceManager.GetString("Nav_AppCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Actions.
        /// </summary>
        public static string Nav_QuickActions {
            get {
                return ResourceManager.GetString("Nav_QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Management.
        /// </summary>
        public static string Nav_ServiceManagement {
            get {
                return ResourceManager.GetString("Nav_ServiceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: {0}.
        /// </summary>
        public static string QuickActions_Failed {
            get {
                return ResourceManager.GetString("QuickActions_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending &apos;{0}&apos; to {1}....
        /// </summary>
        public static string QuickActions_Sending {
            get {
                return ResourceManager.GetString("QuickActions_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success: {0}.
        /// </summary>
        public static string QuickActions_Success {
            get {
                return ResourceManager.GetString("QuickActions_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command failed with status {0}: {1}.
        /// </summary>
        public static string ServiceManagement_CommandFailed {
            get {
                return ResourceManager.GetString("ServiceManagement_CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully sent {0} command..
        /// </summary>
        public static string ServiceManagement_CommandSuccess {
            get {
                return ResourceManager.GetString("ServiceManagement_CommandSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command failed with Unauthorized. Check your secret is correct..
        /// </summary>
        public static string ServiceManagement_CommandUnauthorized {
            get {
                return ResourceManager.GetString("ServiceManagement_CommandUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration saved successfully. Restart the service for these settings to be applied..
        /// </summary>
        public static string ServiceManagement_ConfigSavedSuccess {
            get {
                return ResourceManager.GetString("ServiceManagement_ConfigSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved to UI, but could not find Service config file. Service may not be updated..
        /// </summary>
        public static string ServiceManagement_ConfigSavedWarning {
            get {
                return ResourceManager.GetString("ServiceManagement_ConfigSavedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving configuration: {0}.
        /// </summary>
        public static string ServiceManagement_ConfigSaveError {
            get {
                return ResourceManager.GetString("ServiceManagement_ConfigSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved to UI settings, but failed to update Service config file: {0}. Try running as Administrator..
        /// </summary>
        public static string ServiceManagement_ConfigUpdateFailed {
            get {
                return ResourceManager.GetString("ServiceManagement_ConfigUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed: {0}. Ensure the service is running..
        /// </summary>
        public static string ServiceManagement_ConnectionFailed {
            get {
                return ResourceManager.GetString("ServiceManagement_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error running elevated command: {0}.
        /// </summary>
        public static string ServiceManagement_ElevatedCommandError {
            get {
                return ResourceManager.GetString("ServiceManagement_ElevatedCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start elevated process. User may have cancelled UAC prompt..
        /// </summary>
        public static string ServiceManagement_ElevatedProcessFailed {
            get {
                return ResourceManager.GetString("ServiceManagement_ElevatedProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service installation cancelled..
        /// </summary>
        public static string ServiceManagement_InstallCancelled {
            get {
                return ResourceManager.GetString("ServiceManagement_InstallCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error installing service: {0}.
        /// </summary>
        public static string ServiceManagement_InstallError {
            get {
                return ResourceManager.GetString("ServiceManagement_InstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing service....
        /// </summary>
        public static string ServiceManagement_InstallingService {
            get {
                return ResourceManager.GetString("ServiceManagement_InstallingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install service: {0}.
        /// </summary>
        public static string ServiceManagement_InstallServiceFailed {
            get {
                return ResourceManager.GetString("ServiceManagement_InstallServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid executable path..
        /// </summary>
        public static string ServiceManagement_InvalidExePath {
            get {
                return ResourceManager.GetString("ServiceManagement_InvalidExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port: {0}.
        /// </summary>
        public static string ServiceManagement_InvalidPort {
            get {
                return ResourceManager.GetString("ServiceManagement_InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be between 1 and 65535.
        /// </summary>
        public static string ServiceManagement_PortValidation {
            get {
                return ResourceManager.GetString("ServiceManagement_PortValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start process..
        /// </summary>
        public static string ServiceManagement_ProcessStartFailed {
            get {
                return ResourceManager.GetString("ServiceManagement_ProcessStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting service....
        /// </summary>
        public static string ServiceManagement_RestartingService {
            get {
                return ResourceManager.GetString("ServiceManagement_RestartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restart service: {0}.
        /// </summary>
        public static string ServiceManagement_RestartServiceFailed {
            get {
                return ResourceManager.GetString("ServiceManagement_RestartServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving configuration....
        /// </summary>
        public static string ServiceManagement_SavingConfig {
            get {
                return ResourceManager.GetString("ServiceManagement_SavingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending {0} command to {1}....
        /// </summary>
        public static string ServiceManagement_SendingCommand {
            get {
                return ResourceManager.GetString("ServiceManagement_SendingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service installed successfully. You can now start it..
        /// </summary>
        public static string ServiceManagement_ServiceInstalled {
            get {
                return ResourceManager.GetString("ServiceManagement_ServiceInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service restarted successfully..
        /// </summary>
        public static string ServiceManagement_ServiceRestarted {
            get {
                return ResourceManager.GetString("ServiceManagement_ServiceRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service started successfully..
        /// </summary>
        public static string ServiceManagement_ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceManagement_ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service stopped successfully..
        /// </summary>
        public static string ServiceManagement_ServiceStopped {
            get {
                return ResourceManager.GetString("ServiceManagement_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service uninstalled successfully..
        /// </summary>
        public static string ServiceManagement_ServiceUninstalled {
            get {
                return ResourceManager.GetString("ServiceManagement_ServiceUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service....
        /// </summary>
        public static string ServiceManagement_StartingService {
            get {
                return ResourceManager.GetString("ServiceManagement_StartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service.
        /// </summary>
        public static string ServiceManagement_StartServiceFailed {
            get {
                return ResourceManager.GetString("ServiceManagement_StartServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping service....
        /// </summary>
        public static string ServiceManagement_StoppingService {
            get {
                return ResourceManager.GetString("ServiceManagement_StoppingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop service.
        /// </summary>
        public static string ServiceManagement_StopServiceFailed {
            get {
                return ResourceManager.GetString("ServiceManagement_StopServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service uninstallation cancelled..
        /// </summary>
        public static string ServiceManagement_UninstallCancelled {
            get {
                return ResourceManager.GetString("ServiceManagement_UninstallCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uninstalling service: {0}.
        /// </summary>
        public static string ServiceManagement_UninstallError {
            get {
                return ResourceManager.GetString("ServiceManagement_UninstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling service....
        /// </summary>
        public static string ServiceManagement_UninstallingService {
            get {
                return ResourceManager.GetString("ServiceManagement_UninstallingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to uninstall service: {0}.
        /// </summary>
        public static string ServiceManagement_UninstallServiceFailed {
            get {
                return ResourceManager.GetString("ServiceManagement_UninstallServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_ThemeDark {
            get {
                return ResourceManager.GetString("Settings_ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_ThemeLight {
            get {
                return ResourceManager.GetString("Settings_ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Settings_ThemeSystem {
            get {
                return ResourceManager.GetString("Settings_ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
