# GitHub Automatic Dependency Submission Configuration
#
# This file documents the configuration needed for NuGet dependency submission
# to work correctly with Windows-targeted .NET projects.
#
# IMPORTANT: This is a documentation file. GitHub's automatic dependency submission
# feature does not currently support a `.github/dependency-graph.yml` configuration
# file to specify runner OS directly.
#
# ISSUE: The automatic dependency submission workflow fails because:
# - It defaults to Linux runners (`ubuntu-latest`)
# - This project targets Windows-specific frameworks: `net10.0-windows10.0.26100.0`
# - The project uses WinUI 3 and Windows App SDK which require Windows to build
# - Linux runners cannot restore/build Windows-targeted .NET projects without
#   the `EnableWindowsTargeting` property (which is not practical for WinUI projects)
#
# ERROR FROM FAILED RUN (20799482245):
#   error NETSDK1100: To build a project targeting Windows on this operating system,
#   set the EnableWindowsTargeting property to true.
#
# SOLUTION OPTIONS:
#
# Option 1: Configure Self-Hosted Windows Runners (RECOMMENDED)
# ---------------------------------------------------------------
# 1. Provision one or more self-hosted Windows runners for the repository
#    - See: https://docs.github.com/en/actions/hosting-your-own-runners
# 2. Assign the `dependency-submission` label to each runner
#    - This label tells GitHub to use these runners for automatic dependency submission
# 3. In Repository Settings → Security → Advanced Security → Dependency Graph:
#    - Select "Enabled for labeled runners" instead of just "Enabled"
#
# Once configured, automatic dependency submission will use the Windows runners,
# allowing the .NET restore to succeed for Windows-targeted projects.
#
# Option 2: Use GitHub-Hosted Larger Runners
# -------------------------------------------
# For GitHub Team or GitHub Enterprise Cloud:
# 1. Provision a larger Windows runner at the organization level
#    - Name it: `dependency-submission`
# 2. Give the repository access to this runner
# 3. In Repository Settings → Security → Advanced Security → Dependency Graph:
#    - Select "Enabled for labeled runners"
#
# Option 3: Disable Automatic Submission (NOT RECOMMENDED)
# ---------------------------------------------------------
# - In Repository Settings → Security → Advanced Security:
#    - Disable "Automatic dependency submission"
# - This will prevent dependency graph updates and Dependabot alerts for transitive dependencies
#
# RECOMMENDED CONFIGURATION AFTER IMPLEMENTING OPTION 1 OR 2:
# -------------------------------------------------------------
# The self-hosted Windows runner(s) should have:
# - Windows 10/11 (version 22621 or later)
# - .NET 10 SDK installed
# - Windows SDK 10.0.26100.0 or later
# - Windows App SDK installed
# - NuGet package caching configured for performance
#
# REFERENCE:
# - Existing CI workflow (.github/workflows/ci.yml) successfully builds on `windows-latest`
# - This proves the project can build correctly on Windows runners with .NET 10
#
# For more information:
# - https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-automatic-dependency-submission-for-your-repository
# - https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/using-labels-with-self-hosted-runners

# Desired Runner Configuration (for documentation purposes):
# -----------------------------------------------------------
# If GitHub were to support this configuration file format in the future,
# the desired configuration would be:
#
# runner:
#   os: windows-latest
#   
# dotnet:
#   version: "10.0.x"
#   
# cache:
#   enabled: true
#   paths:
#     - ~/.nuget/packages
#   key-prefix: ${{ runner.os }}-nuget-
#
# environment:
#   DOTNET_NOLOGO: true
#   DOTNET_CLI_TELEMETRY_OPTOUT: true
#   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
